---
title: "cd_biz"
author: "Brook Frye"
date: "9/4/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
source("~/utils/00_load_dependencies.R")
source("code/biz_dsny_complaints_2023.R")

# use bizdt bizshp for the merged business/complaint data
```

#### Map of DSNY complaints related to businesses from 2022 - present. Includes the following complaint types for streets and sidewalks:
- Commercial Disposal Complaint 
- Retailer Complaint
- Dirty Condition

*** 

##### We are sourcing business data from:
- [Vacant storefront registration](https://data.cityofnewyork.us/City-Government/Storefronts-Reported-Vacant-or-Not/92iy-9c3n)
- [DCA licenses](https://nycopendata.socrata.com/Business/Legally-Operating-Businesses/w7w3-xahh/data)

```{r}

cd_biz
int_cd_biz <-
  classInt::classIntervals(cd_biz$n_cmpts_p_biz, n = 6)

pal_biz = leaflet::colorBin(
  # issues with councildown's colorBin
  palette = c("#660000","#1850b5","#ba9f64","#1f3a70","#b3b3ff","#af6d46"),
  bins = int_cd_biz$brks,
  domain = round(cd_biz$n_cmpts_p_biz, 2),
  na.color = "White",
  reverse = TRUE
)

m_biz <- leaflet() %>% 
  addCouncilStyle(add_dists = TRUE) %>% 
  leaflet::addPolygons(data=cd_biz, 
                       fillColor = ~pal_biz(n_cmpts_p_biz), 
                       label = ~paste0(n_cmpts_p_biz), 
                       opacity = 0) %>% 
  addLegend(pal = pal_biz, 
            values = int_cd_biz$brks, 
            position = "topleft", 
            title = "Complaints per Business by <br/> Council District")


mapview::mapshot(m_biz, "visuals/dsny_biz_cmplts_2022-sept2023.html")
```

```{r}
bizdt[, total_ind := sum(industry_cmpt*n_cmpts), by = .(industry)]
ggplot(bizdt, aes(x=total_ind, group=industry, color=industry)) + geom_histogram() + theme_bw()
```


#### Scorecard - Street Cleanliness
```{r}


```

```{r}

```

```{r}

cd_biz <- leaflet(biz_shps) %>% 
  addProviderTiles("CartoDB") %>% 
  addPolygons(weight = .5,
              fillColor = ~pal(nbiz), 
              popup = paste(biz_shps$nbiz, biz_shps$boro_cd), 
              stroke = TRUE, 
              fillOpacity = .9) %>% 
  addLegend(pal = pal, 
            values = biz_shps$nbiz) 
```

